---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    attributes:
      openssh:
        server:
          port: '22'
    run_list:
      - recipe[prl_base::default]
    verifier:
      inspec_tests:
        - test/integration/default
